// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Favorite struct {
	UserID    int32            `json:"userId"`
	RecipeID  int32            `json:"recipeId"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type Recipe struct {
	ID              int32            `json:"id"`
	UserID          pgtype.Int4      `json:"userId"`
	Title           string           `json:"title"`
	Description     string           `json:"description"`
	Type            int32            `json:"type"`
	AssetID         string           `json:"assetId"`
	PrepTimeMinutes pgtype.Int4      `json:"prepTimeMinutes"`
	Servings        pgtype.Int4      `json:"servings"`
	IsPublic        pgtype.Bool      `json:"isPublic"`
	CreatedAt       pgtype.Timestamp `json:"createdAt"`
	UpdatedAt       pgtype.Timestamp `json:"updatedAt"`
}

type RecipeComment struct {
	ID        int32            `json:"id"`
	RecipeID  pgtype.Int4      `json:"recipeId"`
	UserID    pgtype.Int4      `json:"userId"`
	Comment   string           `json:"comment"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type RecipeStep struct {
	ID          int32       `json:"id"`
	RecipeID    pgtype.Int4 `json:"recipeId"`
	StepNumber  int32       `json:"stepNumber"`
	Description string      `json:"description"`
	AssetID     pgtype.Text `json:"assetId"`
}

type User struct {
	ID           int32            `json:"id"`
	Email        string           `json:"email"`
	PasswordHash string           `json:"passwordHash"`
	Bio          string           `json:"bio"`
	AvatarUrl    string           `json:"avatarUrl"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
}
