// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Favorite struct {
	UserID    int32
	RecipeID  int32
	CreatedAt pgtype.Timestamp
}

type Ingredient struct {
	ID   int32
	Name string
}

type Recipe struct {
	ID              int32
	UserID          pgtype.Int4
	Title           string
	Description     string
	Instructions    string
	ImageUrl        string
	PrepTimeMinutes pgtype.Int4
	BrewTimeMinutes pgtype.Int4
	Servings        pgtype.Int4
	IsPublic        pgtype.Bool
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type RecipeComment struct {
	ID        int32
	RecipeID  pgtype.Int4
	UserID    pgtype.Int4
	Comment   string
	CreatedAt pgtype.Timestamp
}

type RecipeIngredient struct {
	ID           int32
	RecipeID     pgtype.Int4
	IngredientID pgtype.Int4
	Quantity     pgtype.Text
}

type RecipeStep struct {
	ID          int32
	RecipeID    pgtype.Int4
	StepNumber  int32
	Description string
	MediaUrl    pgtype.Text
}

type RecipeTag struct {
	RecipeID int32
	TagID    int32
}

type Tag struct {
	ID   int32
	Name string
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	Bio          string
	AvatarUrl    string
	CreatedAt    pgtype.Timestamp
}
